version: "3.9"

services:
  
  db:
    image: postgres:16.2-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "140MB"
  
networks:
  default:
    driver: bridge
    name: rinha_network